before_script:
  - "nohup bundle exec ruby test/live_server.rb &"
  - "sleep 2"

env: LIVE=1

language: ruby

rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - jruby-18mode
  - jruby-19mode
  - rbx-18mode
  - rbx-19mode
