before_install:
  - gem update bundler
  - bundle --version
  - gem update --system 2.1.11
  - gem --version
bundler_args: --standalone --without development
script: RUBYLIB=./bundle script/test

language: ruby

env:
  - SSL=no
  - SSL=yes

matrix:
  allow_failures:
    # random crashes
    - rvm: rbx-18mode
    - rvm: rbx-19mode
    - rvm: rbx-20mode
    - rvm: jruby-18mode
    - rvm: jruby-19mode

rvm:
  - rbx-18mode
  - rbx-19mode
  - rbx-20mode
  - jruby-18mode
  - jruby-19mode
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - 2.0.0
  - 2.1.0
