script: script/test

language: ruby

matrix:
  allow_failures:
    - rvm: ruby-head
  exclude:
    # JRuby + SSL stalls indefinitely on Travis
    # https://travis-ci.org/lostisland/faraday/builds/4568790
    - rvm: jruby-18mode
      env: SSL=yes
    - rvm: jruby-19mode
      env: SSL=yes

env:
  - SSL=no
  - SSL=yes

rvm:
  - rbx-18mode
  - rbx-19mode
  - jruby-18mode
  - jruby-19mode
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - ruby-head
